[package]
name = "ztm"
version = "0.0.4"
description = "ZTM"
authors = ["lindc"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ztm_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "=2.0.0-beta.19", features = [] }

# tauri = { version = "2.0.0-beta", features = ["devtools"] }
[dependencies]
fix-path-env = { git = "https://github.com/tauri-apps/fix-path-env-rs" }
tauri = { version = "=2.0.0-beta.24", features = ["macos-proxy", "unstable", "ios"] }
tauri-utils = "=2.0.0-beta.19"
tauri-runtime = "=2.0.0-beta.20"
tauri-plugin-shell = "=2.0.0-beta.9"
tauri-plugin-process = "=2.0.0-beta.8"
tauri-plugin-http = "=2.0.0-beta.12"
tauri-plugin-os = "=2.0.0-beta.8"
tauri-plugin-fs = "=2.0.0-beta.11"
tauri-plugin-deep-link = "=2.0.0-beta.9"
lazy_static = "1.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2.2"
libloading = "0.7"
j4rs = "0.20.0"
wry = "0.41.0"
# tao = "0.28.1"

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-cli = "2.0.0-beta"

[target.'cfg(any(target_os = "android"))']
linker = "~/Library/Android/sdk/ndk/27.0.11718014/toolchains/llvm/prebuilt/darwin-x86_64/bin"
