[package]
name = "ztm"
version = "0.0.4"
description = "ZTM"
authors = ["lindc"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ztm_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

# tauri = { version = "2.0.0-beta", features = ["devtools"] }
[dependencies]
fix-path-env = { git = "https://github.com/tauri-apps/fix-path-env-rs" }
tauri = { version = "=2.0.0-beta.22", features = ["macos-proxy"] }
tauri-utils = "=2.0.0-beta.17"
tauri-plugin-shell = "=2.0.0-beta.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-process = "=2.0.0-beta.5"
tauri-plugin-http = "=2.0.0-beta.5"
tauri-plugin-os = "=2.0.0-beta.5"
tauri-plugin-fs = "=2.0.0-beta.7"
libloading = "0.7"

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-cli = "2.0.0-beta"

[target.'cfg(any(target_os = "android"))']
linker = "~/Library/Android/sdk/ndk/27.0.11718014/toolchains/llvm/prebuilt/darwin-x86_64/bin"
