name: android-build

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '21'
    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17.0.10'
        distribution: oracle
    - name: Setup Android SDK
      uses: Swisyn/setup-android-sdk@v1
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.5.0
      with:
        # Exact version to use
        ndk-version: r26d
        # Add installed NDK to the Android SDK
        link-to-sdk: true
    - name: Setup Rustup Target
      run: |
        rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
    - name: build ztm
      run: |
        cd gui
        yarn download-ztm-android
    - name: build apk
      run: |
        cd gui
        export JAVA_HOME='/Users/runner/hostedtoolcache/Java_Oracle_jdk/17.0.10/arm64/Contents/Home'
        echo $JAVA_HOME
        export ANDROID_HOME='/Users/runner/Library/Android/sdk'
        echo $ANDROID_HOME
        ls -d $ANDROID_HOME/ndk/* | sort -V | tail -n 1 | xargs basename
        export NDK_HOME="$ANDROID_HOME/ndk/$(ls -d $ANDROID_HOME/ndk/* | sort -V | tail -n 1 | xargs basename)"
        echo $NDK_HOME
        export OPENSSL_DIR='/opt/homebrew/Cellar/openssl@3/3.3.0'
        echo $OPENSSL_DIR
        yarn install
        yarn android-init
        yarn tauri android build
        NODE_OPTIONS="--max-old-space-size=4096" yarn tauri build
        
    - name: Sign apk
      run: |
        echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > app/my-release-key.jks
        jarsigner -verbose -keystore app/my-release-key.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.KEY_ALIAS }}

    - name: Align apk
      run: |
        ${ANDROID_HOME}/build-tools/30.0.3/zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release.apk

    - uses: actions/upload-artifact@v2
      with:
        name: release
        path: ./gui/src-tauri/gen/android/app/universal/release/app-universal-release.apk
