name: android-build

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '21'
    - name: build ztm
      run: |
        cd gui
        yarn download-ztm-android
    - name: build apk
      run: |
        cd gui
        yarn android-init
        yarn tauri android build
        NODE_OPTIONS="--max-old-space-size=4096" yarn tauri build
        
    - name: Sign apk
      run: |
        echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > app/my-release-key.jks
        jarsigner -verbose -keystore app/my-release-key.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.KEY_ALIAS }}

    - name: Align apk
      run: |
        ${ANDROID_HOME}/build-tools/30.0.3/zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release.apk

    - uses: actions/upload-artifact@v2
      with:
        name: release
        path: ./gui/src-tauri/gen/android/app/universal/release/app-universal-release.apk
