name: macos-m1-build

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '21'
    - name: build app
      run: |
        cd gui
        yarn install
        NODE_OPTIONS="--max-old-space-size=4096" yarn build:apps
        git fetch --tags
        yarn build-ztm-macos
        NODE_OPTIONS="--max-old-space-size=4096" yarn build:base

    - name: Rename
      run: mv ./gui/src-tauri/target/release/bundle/dmg/ztm_${{ vars.APP_VERSION }}_aarch64.dmg ./gui/src-tauri/target/release/bundle/dmg/ztm-app-v${{ vars.APP_VERSION }}-macos-arm64.dmg

    - uses: actions/upload-artifact@v3
      with:
        name: ztm-app-v${{ vars.APP_VERSION }}-macos-arm64
        path: ./gui/src-tauri/target/release/bundle/dmg/ztm-app-v${{ vars.APP_VERSION }}-macos-arm64.dmg
