name: macos-m1-build

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '21'
    - name: build app
      run: |
        cd gui
        yarn install
        yarn build-ztm-macos
        NODE_OPTIONS="--max-old-space-size=4096" yarn tauri build
    - uses: actions/upload-artifact@v2
      with:
        name: release
        path: ./gui/src-tauri/target/release/bundle/dmg/ZTMApp_0.0.3_aarch64.dmg
