name: macos-m1-debug

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '21'
    - name: build app
      run: |
        cd gui
        yarn install
        NODE_OPTIONS="--max-old-space-size=4096" yarn build:apps
        yarn build-ztm-macos
        NODE_OPTIONS="--max-old-space-size=4096" yarn build:debug
    - uses: actions/upload-artifact@v3
      with:
        name: release
        path: ./gui/src-tauri/target/debug/bundle/dmg/ztm_${{ vars.APP_VERSION }}_aarch64.dmg
