name: macos-m1-chat-build

on: 
  workflow_dispatch:
  push:
    branches:
      - chat
  pull_request:
    branches:
      - chat

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '21'
    - name: build app
      run: |
        cd gui
        yarn install
        yarn build-ztm-macos
        NODE_OPTIONS="--max-old-space-size=4096" yarn build:chat
    - uses: actions/upload-artifact@v2
      with:
        name: release
        path: ./gui/src-tauri/target/release/bundle/dmg/ZTM_${{ vars.APP_VERSION }}_aarch64.dmg
