# This is a basic workflow that is manually triggered

name: test-secrets

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell

    - name: Debug Secrets
      run: |
        echo "Keystore Password: ${{ secrets.KEYSTORE_BASE64 }}"
        echo "Key Alias: ${{ secrets.KEY_ALIAS }}"

