name: windows-build

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.25.0"  # <--= optional, use most recent 3.25.x version
        ninjaVersion: "^1.11.1"
    - uses: actions/setup-node@v2
      with:
        node-version: '21'
    - run: npm install -g win-node-env
    - name: Install NASM
      run: choco install nasm -y
    - name: build pipy
      run: |
        cd gui
        yarn build-pipy-windows
    - name: build app
      run: |
        cd gui
        yarn install
        set NODE_OPTIONS=--max_old_space_size=4096 && yarn tauri build
    - uses: actions/upload-artifact@v2
      with:
        name: release
        path: ./gui/src-tauri/target/release/bundle/nsis/ZTMesh_0.1.0_x64-setup.exe
